### ISSUE TITLE
数据列表数据量太少会导致查看书籍失败

### ISSUE THREAD

**Issue by 7-bit11** [fluttercandies/flutter_novel#4]
### Version

2.1.1

### Platforms

dart, Android, iOS, macOS, Windows

### Device Model

ALL

### flutter info

```sh
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[!] Flutter (Channel stable, 3.24.4, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
    • Flutter version 3.24.4 on channel stable at D:\Flutter_SDK\flutter
    ! Upstream repository https://github.com/flutter/flutter.git is not the same as FLUTTER_GIT_URL
    • FLUTTER_GIT_URL = https://gitee.com/harmonycommando_flutter/flutter.git
    • Framework revision 603104015d (2 weeks ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Android Studio new\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
    • Visual Studio at D:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34018.315
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Android Studio (version 2024.1)
    • Android Studio at D:\Android Studio new
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2023.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • 23127PN0CC (mobile) • 74f07899 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [版本 10.0.22631.4317]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 130.0.6723.116
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 130.0.2849.68

[!] Network resources
    X An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received
```

### How to reproduce?

一、搜索任意关键字
二、找到目录只有一个的书籍
三、阅读

### Logs

```sh
I/flutter (14473): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14473): │ #0   ReadViewModel.refreshDataNext (package:novel_flutter_bit/n_pages/read/view_model/read_view_model.dart:124:26)
I/flutter (14473): │ #1   _ReadPageState._setNext (package:novel_flutter_bit/n_pages/read/view/read_page.dart:210:34)
I/flutter (14473): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14473): │ 2024-11-08 15:27:58.992
I/flutter (14473): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14473): │ ⛔ NewSearchViewModel _initData error:RangeError (length): Invalid value: Only valid value is 0: 2
I/flutter (14473): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by 7-bit11** [comment]
修改完成。
